// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	redis "github.com/I000000/recly/internal/redis"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

// GetResult provides a mock function with given fields: ctx, taskID
func (_m *Cache) GetResult(ctx context.Context, taskID string) (*redis.RecommendationResult, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetResult")
	}

	var r0 *redis.RecommendationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*redis.RecommendationResult, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *redis.RecommendationResult); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.RecommendationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetResult provides a mock function with given fields: ctx, taskID, result, ttl
func (_m *Cache) SetResult(ctx context.Context, taskID string, result redis.RecommendationResult, ttl time.Duration) error {
	ret := _m.Called(ctx, taskID, result, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, redis.RecommendationResult, time.Duration) error); ok {
		r0 = rf(ctx, taskID, result, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
