// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/I000000/recly/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// LibraryService is an autogenerated mock type for the LibraryService type
type LibraryService struct {
	mock.Mock
}

// AddBook provides a mock function with given fields: ctx, userID, bookID
func (_m *LibraryService) AddBook(ctx context.Context, userID string, bookID string) error {
	ret := _m.Called(ctx, userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for AddBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, bookID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddMovie provides a mock function with given fields: ctx, userID, movieID
func (_m *LibraryService) AddMovie(ctx context.Context, userID string, movieID string) error {
	ret := _m.Called(ctx, userID, movieID)

	if len(ret) == 0 {
		panic("no return value specified for AddMovie")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, movieID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBooks provides a mock function with given fields: ctx, userID
func (_m *LibraryService) GetBooks(ctx context.Context, userID string) ([]domain.LikedBook, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBooks")
	}

	var r0 []domain.LikedBook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.LikedBook, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.LikedBook); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.LikedBook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMovies provides a mock function with given fields: ctx, userID
func (_m *LibraryService) GetMovies(ctx context.Context, userID string) ([]domain.LikedMovie, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMovies")
	}

	var r0 []domain.LikedMovie
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.LikedMovie, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.LikedMovie); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.LikedMovie)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveBook provides a mock function with given fields: ctx, userID, bookID
func (_m *LibraryService) RemoveBook(ctx context.Context, userID string, bookID string) error {
	ret := _m.Called(ctx, userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, bookID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveMovie provides a mock function with given fields: ctx, userID, movieID
func (_m *LibraryService) RemoveMovie(ctx context.Context, userID string, movieID string) error {
	ret := _m.Called(ctx, userID, movieID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMovie")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, movieID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLibraryService creates a new instance of LibraryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLibraryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LibraryService {
	mock := &LibraryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
