// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/I000000/recly/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// LibraryRepository is an autogenerated mock type for the LibraryRepository type
type LibraryRepository struct {
	mock.Mock
}

// AddLikedBook provides a mock function with given fields: ctx, userID, bookID
func (_m *LibraryRepository) AddLikedBook(ctx context.Context, userID string, bookID string) error {
	ret := _m.Called(ctx, userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for AddLikedBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, bookID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddLikedMovie provides a mock function with given fields: ctx, userID, movieID
func (_m *LibraryRepository) AddLikedMovie(ctx context.Context, userID string, movieID string) error {
	ret := _m.Called(ctx, userID, movieID)

	if len(ret) == 0 {
		panic("no return value specified for AddLikedMovie")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, movieID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLikedBooks provides a mock function with given fields: ctx, userID
func (_m *LibraryRepository) GetLikedBooks(ctx context.Context, userID string) ([]domain.LikedBook, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetLikedBooks")
	}

	var r0 []domain.LikedBook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.LikedBook, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.LikedBook); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.LikedBook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLikedMovies provides a mock function with given fields: ctx, userID
func (_m *LibraryRepository) GetLikedMovies(ctx context.Context, userID string) ([]domain.LikedMovie, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetLikedMovies")
	}

	var r0 []domain.LikedMovie
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.LikedMovie, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.LikedMovie); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.LikedMovie)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveLikedBook provides a mock function with given fields: ctx, userID, bookID
func (_m *LibraryRepository) RemoveLikedBook(ctx context.Context, userID string, bookID string) error {
	ret := _m.Called(ctx, userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveLikedBook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, bookID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveLikedMovie provides a mock function with given fields: ctx, userID, movieID
func (_m *LibraryRepository) RemoveLikedMovie(ctx context.Context, userID string, movieID string) error {
	ret := _m.Called(ctx, userID, movieID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveLikedMovie")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, movieID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLibraryRepository creates a new instance of LibraryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLibraryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LibraryRepository {
	mock := &LibraryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
