// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/I000000/recly/internal/domain"

	mock "github.com/stretchr/testify/mock"

	redis "github.com/I000000/recly/internal/redis"
)

// RecommendationService is an autogenerated mock type for the RecommendationService type
type RecommendationService struct {
	mock.Mock
}

// DeleteSavedRecommendation provides a mock function with given fields: ctx, id
func (_m *RecommendationService) DeleteSavedRecommendation(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSavedRecommendation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetHistory provides a mock function with given fields: ctx, userID
func (_m *RecommendationService) GetHistory(ctx context.Context, userID string) ([]domain.RecommendationHistory, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 []domain.RecommendationHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.RecommendationHistory, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.RecommendationHistory); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RecommendationHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetResult provides a mock function with given fields: ctx, taskID
func (_m *RecommendationService) GetResult(ctx context.Context, taskID string) (*redis.RecommendationResult, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetResult")
	}

	var r0 *redis.RecommendationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*redis.RecommendationResult, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *redis.RecommendationResult); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.RecommendationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSavedRecommendations provides a mock function with given fields: ctx, userID
func (_m *RecommendationService) GetSavedRecommendations(ctx context.Context, userID string) ([]domain.SavedRecommendation, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSavedRecommendations")
	}

	var r0 []domain.SavedRecommendation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.SavedRecommendation, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.SavedRecommendation); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SavedRecommendation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Request provides a mock function with given fields: ctx, userID, selectedIDs, weights, excludeIDs, direction, contextual
func (_m *RecommendationService) Request(ctx context.Context, userID string, selectedIDs []string, weights map[string]float64, excludeIDs []string, direction string, contextual bool) (string, error) {
	ret := _m.Called(ctx, userID, selectedIDs, weights, excludeIDs, direction, contextual)

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, map[string]float64, []string, string, bool) (string, error)); ok {
		return rf(ctx, userID, selectedIDs, weights, excludeIDs, direction, contextual)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, map[string]float64, []string, string, bool) string); ok {
		r0 = rf(ctx, userID, selectedIDs, weights, excludeIDs, direction, contextual)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, map[string]float64, []string, string, bool) error); ok {
		r1 = rf(ctx, userID, selectedIDs, weights, excludeIDs, direction, contextual)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveRecommendation provides a mock function with given fields: ctx, userID, fromType, fromID, toType, toID
func (_m *RecommendationService) SaveRecommendation(ctx context.Context, userID string, fromType string, fromID string, toType string, toID string) (*domain.SavedRecommendation, error) {
	ret := _m.Called(ctx, userID, fromType, fromID, toType, toID)

	if len(ret) == 0 {
		panic("no return value specified for SaveRecommendation")
	}

	var r0 *domain.SavedRecommendation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (*domain.SavedRecommendation, error)); ok {
		return rf(ctx, userID, fromType, fromID, toType, toID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) *domain.SavedRecommendation); ok {
		r0 = rf(ctx, userID, fromType, fromID, toType, toID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SavedRecommendation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = rf(ctx, userID, fromType, fromID, toType, toID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRecommendationService creates a new instance of RecommendationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecommendationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecommendationService {
	mock := &RecommendationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
