// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/I000000/recly/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// RecommendationRepository is an autogenerated mock type for the RecommendationRepository type
type RecommendationRepository struct {
	mock.Mock
}

// DeleteSavedRecommendation provides a mock function with given fields: ctx, id
func (_m *RecommendationRepository) DeleteSavedRecommendation(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSavedRecommendation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetHistory provides a mock function with given fields: ctx, userID
func (_m *RecommendationRepository) GetHistory(ctx context.Context, userID string) ([]domain.RecommendationHistory, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 []domain.RecommendationHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.RecommendationHistory, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.RecommendationHistory); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RecommendationHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSavedRecommendations provides a mock function with given fields: ctx, userID
func (_m *RecommendationRepository) GetSavedRecommendations(ctx context.Context, userID string) ([]domain.SavedRecommendation, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSavedRecommendations")
	}

	var r0 []domain.SavedRecommendation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.SavedRecommendation, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.SavedRecommendation); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SavedRecommendation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveHistory provides a mock function with given fields: ctx, entry
func (_m *RecommendationRepository) SaveHistory(ctx context.Context, entry *domain.RecommendationHistory) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for SaveHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RecommendationHistory) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveRecommendation provides a mock function with given fields: ctx, rec
func (_m *RecommendationRepository) SaveRecommendation(ctx context.Context, rec *domain.SavedRecommendation) error {
	ret := _m.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for SaveRecommendation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SavedRecommendation) error); ok {
		r0 = rf(ctx, rec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRecommendationRepository creates a new instance of RecommendationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecommendationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecommendationRepository {
	mock := &RecommendationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
