// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/I000000/recly/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// SavedItemService is an autogenerated mock type for the SavedItemService type
type SavedItemService struct {
	mock.Mock
}

// DeleteSavedItem provides a mock function with given fields: ctx, id
func (_m *SavedItemService) DeleteSavedItem(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSavedItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSavedItems provides a mock function with given fields: ctx, userID
func (_m *SavedItemService) GetSavedItems(ctx context.Context, userID string) ([]domain.SavedItem, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSavedItems")
	}

	var r0 []domain.SavedItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.SavedItem, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.SavedItem); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SavedItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveItem provides a mock function with given fields: ctx, userID, itemType, itemID
func (_m *SavedItemService) SaveItem(ctx context.Context, userID string, itemType string, itemID string) (*domain.SavedItem, error) {
	ret := _m.Called(ctx, userID, itemType, itemID)

	if len(ret) == 0 {
		panic("no return value specified for SaveItem")
	}

	var r0 *domain.SavedItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.SavedItem, error)); ok {
		return rf(ctx, userID, itemType, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.SavedItem); ok {
		r0 = rf(ctx, userID, itemType, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SavedItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userID, itemType, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSavedItemService creates a new instance of SavedItemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSavedItemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SavedItemService {
	mock := &SavedItemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
