// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/I000000/recly/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// SearchService is an autogenerated mock type for the SearchService type
type SearchService struct {
	mock.Mock
}

// GetGenres provides a mock function with given fields: itemType
func (_m *SearchService) GetGenres(itemType string) ([]string, error) {
	ret := _m.Called(itemType)

	if len(ret) == 0 {
		panic("no return value specified for GetGenres")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(itemType)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(itemType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(itemType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetItems provides a mock function with given fields: ids, itemType
func (_m *SearchService) GetItems(ids []string, itemType string) ([]domain.ItemDetail, error) {
	ret := _m.Called(ids, itemType)

	if len(ret) == 0 {
		panic("no return value specified for GetItems")
	}

	var r0 []domain.ItemDetail
	var r1 error
	if rf, ok := ret.Get(0).(func([]string, string) ([]domain.ItemDetail, error)); ok {
		return rf(ids, itemType)
	}
	if rf, ok := ret.Get(0).(func([]string, string) []domain.ItemDetail); ok {
		r0 = rf(ids, itemType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ItemDetail)
		}
	}

	if rf, ok := ret.Get(1).(func([]string, string) error); ok {
		r1 = rf(ids, itemType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: query
func (_m *SearchService) Search(query string) ([]domain.ItemDetail, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []domain.ItemDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.ItemDetail, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.ItemDetail); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ItemDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchWithFilters provides a mock function with given fields: query, itemType, genre, sort, limit, offset
func (_m *SearchService) SearchWithFilters(query string, itemType string, genre string, sort string, limit int, offset int) ([]domain.ItemDetail, error) {
	ret := _m.Called(query, itemType, genre, sort, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SearchWithFilters")
	}

	var r0 []domain.ItemDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, int, int) ([]domain.ItemDetail, error)); ok {
		return rf(query, itemType, genre, sort, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, int, int) []domain.ItemDetail); ok {
		r0 = rf(query, itemType, genre, sort, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ItemDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, int, int) error); ok {
		r1 = rf(query, itemType, genre, sort, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSearchService creates a new instance of SearchService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSearchService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SearchService {
	mock := &SearchService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
