// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/I000000/recly/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ViewedItemService is an autogenerated mock type for the ViewedItemService type
type ViewedItemService struct {
	mock.Mock
}

// GetRecentViews provides a mock function with given fields: ctx, userID, limit
func (_m *ViewedItemService) GetRecentViews(ctx context.Context, userID string, limit int) ([]domain.ViewedItem, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentViews")
	}

	var r0 []domain.ViewedItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]domain.ViewedItem, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []domain.ViewedItem); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ViewedItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecordView provides a mock function with given fields: ctx, userID, itemType, itemID
func (_m *ViewedItemService) RecordView(ctx context.Context, userID string, itemType string, itemID string) error {
	ret := _m.Called(ctx, userID, itemType, itemID)

	if len(ret) == 0 {
		panic("no return value specified for RecordView")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, itemType, itemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewViewedItemService creates a new instance of ViewedItemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewViewedItemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ViewedItemService {
	mock := &ViewedItemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
